// Generated by FlutterFire CLI — run `make firebase-configure` to regenerate.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Run `make firebase-configure` to fill these in automatically ──────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCenkOYp8wywCYuXit2ljDKMtvapubm5bU',
    appId: '1:960238258391:web:e7cbd83b55f288e7ff8892',
    messagingSenderId: '960238258391',
    projectId: 'geoping-b30a1',
    authDomain: 'geoping-b30a1.firebaseapp.com',
    storageBucket: 'geoping-b30a1.firebasestorage.app',
    measurementId: 'G-MDW2P0H8H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNdPR09wf3DnsGaq936Tohnyub3yrwKks',
    appId: '1:960238258391:android:af0a69a5816160d8ff8892',
    messagingSenderId: '960238258391',
    projectId: 'geoping-b30a1',
    storageBucket: 'geoping-b30a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHHraWHHsAoXlpCI9aa_zuJdwUzwLk4C8',
    appId: '1:960238258391:ios:3f5430837bf7aaaaff8892',
    messagingSenderId: '960238258391',
    projectId: 'geoping-b30a1',
    storageBucket: 'geoping-b30a1.firebasestorage.app',
    iosBundleId: 'com.blackvikings.geoping',
  );

}